export const REHYDRATION_COMPLETE = "REHYDRATION_COMPLETE";

export const GET_PAGE_REQUEST = "GET_PAGE_REQUEST";
export const GET_PAGE_SUCCESS = "GET_PAGE_SUCCESS";
export const GET_PAGE_FAILURE = "GET_PAGE_FAILURE";

export const SET_UPVOTE_REQUEST = "SET_UPVOTE_REQUEST";
export const SET_UPVOTE_SUCCESS = "SET_UPVOTE_SUCCESS";
export const SET_UPVOTE_FAILURE = "SET_UPVOTE_FAILURE";

export const SET_HIDE_REQUEST = "SET_HIDE_REQUEST";
export const SET_HIDE_SUCCESS = "SET_HIDE_SUCCESS";
export const SET_HIDE_FAILURE = "SET_HIDE_FAILURE";
